apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functions.faas.example.com
spec:
  group: faas.example.com
  names:
    kind: Function
    plural: functions
    singular: function
    shortNames:
      - fn
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - code
                - runtime
                - maxReplicas
              properties:
                code:
                  type: string
                  description: "Python 源码字符串"
                runtime:
                  type: string
                  description: "运行时标识，例如 python3.9"
                minReplicas:
                  type: integer
                  format: int32
                  minimum: 0
                  default: 0
                  description: "最小副本数，默认 0"
                maxReplicas:
                  type: integer
                  format: int32
                  minimum: 1
                  description: "最大副本数，必须 >= 1 且 >= minReplicas"
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "当前 Function 资源的控制面状态"
                reason:
                  type: string
                  description: "最近一次失败的原因（如有）"
                observedGeneration:
                  type: integer
                  format: int64
                deploymentName:
                  type: string
                serviceName:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Runtime
          type: string
          jsonPath: .spec.runtime
        - name: Min
          type: integer
          jsonPath: .spec.minReplicas
        - name: Max
          type: integer
          jsonPath: .spec.maxReplicas
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp