# 保存为 function-hello.yaml
apiVersion: faas.example.com/v1alpha1
kind: Function
metadata:
  name: calculator
  namespace: default
spec:
  code: |
    def main():
      a = 1
      b = 2
      c = a + b
      print(" c: ", c)
      return c
  runtime: python3.9
  minReplicas: 0
  maxReplicas: 3